# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python3 -m pip install --user pipx
          python3 -m pipx ensurepath
          pipx install poetry==1.6.1
          poetry install --all-extras --only main --no-interaction
      - name: Build and publish
        run: |
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry build
          poetry publish -u __token__ -p ${{ secrets.PYPI_TOKEN }} --repository testpypi
